### ISSUE TITLE
use #general as default slack_channel if config is not set

### ISSUE THREAD

**Issue by JuanCrg90** [Calzada-Code/remote-coffee-slack#9]
Currently, you must specify `config.slack_channel` in the config block to be able to perform the request.

```ruby
RemoteCoffeeSlack.configure do |config|
  config.slack_bot_token = your-Bot-User-OAuth-Access-Token
  config.slack_channel = the-slack-channel-what-you-will-take-as-water-cooler
end
```

Update the code touse `#general` if no `slack_channel` is set.

**Comment by ananichev** [comment]
Hey @JuanCrg90, could you please review my PR https://github.com/Calzada-Code/remote-coffee-slack/pull/13
